/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2025-01-09 08:59:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.java.jdbc.model.gender;
import com.java.jdbc.model.Employ;
import com.java.jdbc.dao.EmployDaoImp;
import com.java.jdbc.dao.EmployDao;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Connection;

public final class AddEmploy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form method=\"get\" action=\"AddEmploy.jsp\">\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t\tEmploy No : \r\n");
      out.write("\t\t\t<input type=\"number\" name=\"empno\" /> <br/><br/>\r\n");
      out.write("\t\t\tEmploy Name : \r\n");
      out.write("\t\t\t<input type=\"text\" name=\"name\" /> <br/><br/>\r\n");
      out.write("\t\t\tGender : \r\n");
      out.write("\t\t\t<select name=\"gender\">\r\n");
      out.write("\t\t\t\t<option value=\"Male\">Male</option>\r\n");
      out.write("\t\t\t\t<option value=\"Female\">Female</option>\r\n");
      out.write("\t\t\t</select> <br/><br/>\r\n");
      out.write("\t\t\tDepartment :\r\n");
      out.write("\t\t\t<select name=\"dept\">\r\n");
      out.write("\t\t\t\t<option value=\"Java\">Java</option>\r\n");
      out.write("\t\t\t\t<option value=\"SQL\">Sql</option>\r\n");
      out.write("\t\t\t\t<option value=\"React\">React</option>\r\n");
      out.write("\t\t\t</select> <br/>\r\n");
      out.write("\t\t\tDesignation : \r\n");
      out.write("\t\t\t<select name=\"desig\">\r\n");
      out.write("\t\t\t\t<option value=\"ASE\">Ase</option>\r\n");
      out.write("\t\t\t\t<option value=\"SE\">SE</option>\r\n");
      out.write("\t\t\t\t<option value=\"TL\">TL</option>\r\n");
      out.write("\t\t\t\t<option value=\"Manager\">Manager</option>\r\n");
      out.write("\t\t\t</select> <br/>\r\n");
      out.write("\t\t\tBasic : \r\n");
      out.write("\t\t\t<input type=\"number\" name=\"basic\" /> <br/><br/>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Add Employ\" />\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t");

		if (request.getParameter("empno")!=null && request.getParameter("basic")!=null) {
			EmployDao dao = new EmployDaoImp();
			Employ employ = new Employ();
			employ.setEmpno(Integer.parseInt(request.getParameter("empno")));
			employ.setEname(request.getParameter("ename"));
			employ.setGender(gender.valueOf(request.getParameter("gender")));
			employ.setDept(request.getParameter("dept"));
			employ.setDesig(request.getParameter("desig"));
			employ.setBasic(Double.parseDouble(request.getParameter("basic")));
			dao.addEmploy(employ);
	
      out.write("\r\n");
      out.write("\t\t");
      if (true) {
        _jspx_page_context.forward("EmployTable.jsp");
        return;
      }
      out.write('\r');
      out.write('\n');
      out.write('	');

		}
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
